### ISSUE TITLE
Device uptime sensor

### ISSUE THREAD

**Issue by to4ko** [dentra/esphome-components#12]
is there is something wrong with uptime sensor?

![image](https://user-images.githubusercontent.com/45161980/139821009-1aae57b7-fa6d-4fa4-947d-b8c254606b62.png)

the code 
`external_components:
  - source: github://dentra/esphome-components

sensor:
  - platform: startup
    name: Device Uptime`

**Comment by dentra** [comment]
Do you sync the time with HA or a time server?

**Comment by dentra** [comment]
You could sync your HA with time server, so will get the right results too

**Comment by to4ko** [comment]
ш

> You could sync your HA with time server, so will get the right results too

it's already synced but the result is not what i was expected. once changed in esphome from ha time to time server - everything gets back to normal
