### ISSUE TITLE
miot_ylai003

### ISSUE THREAD

**Issue by artur-nk** [dentra/esphome-components#14]
Hello, I installed your component (mipt_ylai003), everything works fine, everything is displayed in the esp home logs. But I can't figure out how to use it in the home assistant, since my button is not displayed there.

**Comment by dentra** [comment]
Did you succeed?

This component allow you make automations on device events. For example you can turn on some light when button click event occurs. Or if you want you can create template sensor and change it state in automation and this sensor will be published in HA.

**Comment by artur-nk** [comment]
Yes, everything worked out, I figured it out myself.

вс, 14 нояб. 2021 г. в 12:58, dentra ***@***.***>:
