### ISSUE TITLE
ZMAI90v1 error in update

### ISSUE THREAD

**Issue by jasimancas** [dentra/esphome-components#15]
When I try to upgrade to version 2021.10 or 2021.11 I get this error.

Do I have to make any changes?

![image](https://user-images.githubusercontent.com/15717847/142198270-ab21badb-e4ad-4497-aaca-a3c5cd135e00.png)

**Comment by dentra** [comment]
Unfortunately it is not tested with 2021.11 yet. I can look it tomorrow

**Comment by dentra** [comment]
done

**Comment by dentra** [comment]
did you suceed?

**Comment by jasimancas** [comment]
Yes! Thanks!
