### ISSUE TITLE
How install mccgq02hl...?

### ISSUE THREAD

**Issue by arek156** [dentra/esphome-components#2]
Hi
I would like to ask and ask for help on how to install the mccgq02hl add-on.
I already have a few esphome additions but I haven't installed any external components yet.
Here is my file, I did everything as described on github but unfortunately I cannot complete the compilation.

`esphome:
  name: new-ble
  platform: ESP32
  board: nodemcu-32s

external_components:
  - source: github://dentra/esphome-components

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "xxxxxx"

wifi:
  ssid: "Hxxxxx"
  password: "xxxxxx"
  manual_ip:
    static_ip: xxxxxxx
    gateway: xxxxxx
    subnet: xxxxxx

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "New-Ble Fallback Hotspot"
    password: "xxxxxxx"

captive_portal:

esp32_ble_tracker:

binary_sensor:
  - platform: miot_mccgq02hl
    mac_address: "xxxxxxxxxx"
    bindkey: "xxxxxxxxxxxx"
    name: "MCCGQ02HL Door/Window Sensor"
    light:
      name: "MCCGQ02HL Light"
    alert:
      name: "MCCGQ02HL Alert"
    battery_level:
      name: "MCCGQ02HL Battery Level"

In file included from src/esphome/components/miot/automation.h:6:0,
                 from src/esphome/components/miot/automation.cpp:5:
src/esphome/components/miot/miot.h:7:46: fatal error: esphome/components/sensor/sensor.h: No such file or directory
compilation terminated.
*** [/data/new-ble/.pioenvs/new-ble/src/esphome/components/miot/automation.cpp.o] Error 1
========================= [FAILED] Took 13.03 seconds =========================`

**Comment by dentra** [comment]
thanks for reporting. fixed
