### ISSUE TITLE
format_hex_pretty not declared 

### ISSUE THREAD

**Issue by gianlucaf81** [dentra/esphome-components#20]
EDIT: It compiled fine using the dev release of ESPHome. (find solution on https://github.com/esphome/feature-requests/issues/1469)

i have this error when compiling.
the code previously worked, nothing has been changed.

src/esphome/components/miot/miot.cpp:54:76: error: 'format_hex_pretty' was not declared in this scope ESP_LOGW(TAG, "Invalid MiBeacon data length: %s", format_hex_pretty(raw).c_str()); 

![image](https://user-images.githubusercontent.com/39622729/152495147-c735658c-554d-4c6d-9378-74900ba7ec96.png)

[error.txt](https://github.com/dentra/esphome-components/files/8005321/error.txt)

**Comment by dentra** [comment]
You need to upgrade ESPHome to latest version

**Comment by dentra** [comment]
The problem is most likely solved. Issue will be closed soon.
