### ISSUE TITLE
Support for soocare.toothbrush.x3

### ISSUE THREAD

**Issue by mihsu81** [dentra/esphome-components#37]
Hi @dentra,

Would it be possible to add support for the Soocas SMI-X3 toothbrush, based on he information collected by prototux here: https://github.com/wiecosystem/Bluetooth/blob/master/doc/devices/soocare.toothbrush.m1.md?
I've checked the custom services and characteristics and they're identical between the m1 and x3.

Thanks in advance.

**Comment by dentra** [comment]
Hi @mihsu81, unfortunately I do not have any plans to support Soocas toothbrushes yet :(
I have changed my dead X5 to X3U (without BLE) one and happy with it :)
