### ISSUE TITLE
Bluetooth Lock Aqara N100 support

### ISSUE THREAD

**Issue by xrust83** [dentra/esphome-components#48]
Good day. Could you please add support for smart lock Aqara N100 ZNMS16LM. There are 2 versions of the Zigbee + Bluetooth lock that works with the AqaraHome application, and a simple Bluetooth version that works with the MiHome application. Both versions of the lock support homekit but only show the button to open the lock. The lock has a doorbell button and can be automated in MiHome - "if you press the bell, it plays a ringtone on the MiHub", but I want to transfer the bell button to the homekit to play the bell on my homepods. I am ready to do all the experiments with the lock to determine the parameters you need for this
![IMG_5352](https://github.com/dentra/esphome-components/assets/58448955/6002b46b-6466-4275-b39a-cb475286a649)
![IMG_5353](https://github.com/dentra/esphome-components/assets/58448955/822ba222-6763-47e4-a74c-c540c9e69c48)
![IMG_5354](https://github.com/dentra/esphome-components/assets/58448955/87ba9dbc-ea4b-4603-801f-224875d7342f)
![IMG_5355](https://github.com/dentra/esphome-components/assets/58448955/05bc686c-1e50-457b-b299-9d22a2c3b963)

**Comment by dentra** [comment]
unfortunately I don't have this device

**Comment by dentra** [comment]
Maybe later
