### ISSUE TITLE
How can i get a MAC Address from miot_ylyk01yl?

### ISSUE THREAD

**Issue by onetabsen** [dentra/esphome-components#49]
Good afternoon!

I have studied your repository and found two ways to interact and find the binding key for the ylyk01yl remote control. 

However, after trying your examples, I still don't understand where to get the BLE MAC address from? At the moment I have 4 remote controls and 3 more at a friend's house. Each remote control has its own MAC address. I want to connect to ESP 32, but I need to specify a specific address. How do I find and then automatically pass this address to the "mac_address: <device-mac address"> function automatically?

Perhaps it is possible, but I do not know enough information for this, since I have not encountered YAML and ESP HOME before.

**Comment by dentra** [comment]
Hello!
Hello, unfortunately you can't do it automatically.
You need to use some ble scanners, for example use https://play.google.com/store/apps/details?id=uk.co.alt236.btlescan. run "scan" and push any button on your remte. Find entry "yee-rc" or "yeerc", open it and copy address.

If you are lucky and your remote is not encrypted that all. If your remote is encryped you additionally need to get encryption key. It can be done by using my other component or via [python script](https://github.com/rexbut/mikettle/blob/master/get_beacon_key.py)
