### ISSUE TITLE
Xiaomi Mijia Night Light 2 (MJYD02YL) - longer detection time?

### ISSUE THREAD

**Issue by rwjack** [dentra/esphome-components#51]
Hey, could these components help with having the light detect movement for longer? 

Even though I configured the light to stay awake for 60 seconds in the Mi app, it keeps randomly turning off, even when there is movement.

**Comment by dentra** [comment]
Could you please share logs?

**Comment by rwjack** [comment]
Just to clarify, I haven't configured anything yet because I'm still waiting on an esp32 to use as a BT proxy, but I'm just investigating if this is worth implementing for my use case.

**Comment by rwjack** [comment]
I think this is what would work: https://esphome.io/components/bluetooth_proxy.html

Just to confirm, if the proxy can forward BLE advertisements to HA, that means I can set the light activation time to longer than 60s via this component?

Although I cannot turn the light on and off manually?

**Comment by rwjack** [comment]
I got the BT proxy up and running, and connected to the lights using: https://github.com/al-one/hass-xiaomi-miot

Although the integration doesn't expose an option to toggle the lights on or off.

Can your component do so?

**Comment by dentra** [comment]
I bought this device and research it.

**Comment by ov1d1u** [comment]
Any updates, @dentra? I also looked into this and I see that there are some values written on the `00000101-0065-6c62-2e74-6f696d2e696d` characteristic when turning the light on or off:

```
OFF: 0d00891914aed72db5b0
ON:  0e006d7f8326c7edae48
```

and in another session:
```
OFF: 0d00c0220da32b2e2b8f
ON:  0e004c308167a88e0fba
```

It seems that the first byte is some kind of counter, the second is always `00`, but the rest differs a lot which makes me think there is some kind of encryption/scrambling.

**Comment by dentra** [comment]
It is not possible to control on/off manually. 
It is only possibly to change interval of reporting via MiHome.

**Comment by ov1d1u** [comment]
@dentra You can control the night light mode through the app, when you are directly connected to the light:

![Screenshot_20240205_112808_Mi Home](https://github.com/dentra/esphome-components/assets/1385202/304bcf34-d1cd-4678-9f60-5bb7c9bda294)
