### ISSUE TITLE
I can't compile the file, I don't have enough knowledge

### ISSUE THREAD

**Issue by xrust83** [dentra/esphome-components#6]
help me install your plugin. I add the text from the example to the bluetooth_hub.yaml file, but I get an error when cospiling with the esphome run bluetooth_hub.yaml command

python version 3.10
esphome 2021.9.3
macOS 11.6 Big Sur

If possible, make a complete schedule of commands how to download or download missing data by command

`xrust@MacBook-Pro-Wadim documents % esphome run bluetooth_hub.yaml
INFO Reading configuration bluetooth_hub.yaml...
INFO Cloning https://github.com/dentra/esphome-components.git@None
Failed config

external_components: [source bluetooth_hub.yaml:11]
  - [source bluetooth_hub.yaml:11]
    
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun.
    source: github://dentra/esphome-components [source bluetooth_hub.yaml:11]
xrust@MacBook-Pro-Wadim documents % 
`

**Comment by dentra** [comment]
Hi! It looks like is something wrong with your environment. Try using this solution: https://stackoverflow.com/questions/52522565/git-is-not-working-after-macos-update-xcrun-error-invalid-active-developer-pa
